name: cook_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  connectivity_plus: ^7.3.1
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.1.1
  http: ^1.6.0
  intl: ^0.20.3
  mobile_scanner: ^7.4.2
  package_info_plus: ^10.2.1
  printing: ^5.15.1
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  shorebird_code_push: ^2.0.7
  supabase_flutter: ^2.17.2
  url_launcher: ^6.3.2
  youtube_player_flutter: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/i18n/
